<h1>Notebook to get latitude and longitude of each neighbourhood </h1>

<h5>Let us start by importing pandas dataframe and csv file from last week containing needed data to be worked on this week,imported via read_csv</h5>

In [2]:
import pandas as pd
neigh_df=pd.read_csv("Neighbourhoods.csv")
neigh_df.head()

  Postal Code      Borough                           Neighbourhood
0         M1B  Scarborough                          Malvern, Rouge
1         M1C  Scarborough  Rouge Hill, Port Union, Highland Creek
2         M1E  Scarborough       Guildwood, Morningside, West Hill
3         M1G  Scarborough                                  Woburn
4         M1H  Scarborough                               Cedarbrae

<h5>
<a href="https://cocl.us/Geospatial_data">This is url of csv file containing co-ordinates of each postal code which is converted to another dataframe via read_csv </a> <br>

In [3]:
loc_url="https://cocl.us/Geospatial_data"
loc_df=pd.read_csv(loc_url)
loc_df.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

<h5> To merge dataframes based on common postal code </h5>

In [4]:
geo_df=pd.merge(neigh_df,loc_df,on="Postal Code")
geo_df.head()

,Postal Code,Borough,Neighbourhood,Latitude,Longitude
0,M1B,Scarborough,"Malvern, Rouge",43.806686,-79.194353
1,M1C,Scarborough,"Rouge Hill, Port Union, Highland Creek",43.784535,-79.160497
2,M1E,Scarborough,"Guildwood, Morningside, West Hill",43.763573,-79.188711
3,M1G,Scarborough,Woburn,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,43.773136,-79.239476

<h5> To check if final dataframe matches one specified in instructions </h5>

In [5]:
col_nam = ["Postal Code", "Borough", "Neighbourhood","Latitude","Longitude"]
check_frame = pd.DataFrame(columns=col_nam)

pc_list= ["M5G", "M2H", "M4B", "M1J", "M4G", "M4M", "M1R", "M9V", "M9L", "M5V", "M1B", "M5A"]

for pc in pc_list:
    check_frame = check_frame.append(geo_df[geo_df["Postal Code"]==pc], ignore_index=True)
    
check_frame

,Postal Code,Borough,Neighbourhood,Latitude,Longitude
0,M5G,Downtown Toronto,Central Bay Street,43.657952,-79.387383
1,M2H,North York,Hillcrest Village,43.803762,-79.363452
2,M4B,East York,"Parkview Hill, Woodbine Gardens",43.706397,-79.309937
3,M1J,Scarborough,Scarborough Village,43.744734,-79.239476
4,M4G,East York,Leaside,43.709060,-79.363452
5,M4M,East Toronto,Studio District,43.659526,-79.340923
6,M1R,Scarborough,"Wexford, Maryvale",43.750072,-79.295849
7,M9V,Etobicoke,"South Steeles, Silverstone, Humbergate, Jamest...",43.739416,-79.588437
8,M9L,North York,Humber Summit,43.756303,-79.565963
9,M5V,Downtown Toronto,"CN Tower, King and Spadina, Railway Lands, Har...",43.628947,-79.394420
10,M1B,Scarborough,"Malvern, Rouge",43.806686,-79.194353
11,M5A,Downtown Toronto,"Regent Park, Harbourfront",43.654260,-79.360636

<h5> To export above dataframe as csv file for ease of use next week </h5>

In [6]:
geo_df.to_csv("Coordinates.csv",index=False)